### ISSUE TITLE
Feature: Wrap onscreen messaging automatically

### ISSUE THREAD

**Issue by pghvlaans** [pghvlaans/sbotools#16]
Some things shouldn't be wrapped because they might be piped to other commands (reverse dependency reports from `sbofind`, for example), but prompts and simple onscreen messages could be.

**Comment by pghvlaans** [comment]
@shamefulCake1 A setting to turn off wrapping would be very straightforward.

I'd like to ask, though, was there something in particular that was causing trouble? Output that you wanted to pipe, maybe?

**Comment by shamefulCake1** [comment]
I very often resize my terminal windows and change font size to fit the current window layout. So sometimes my terminal is much wider than 73 characters, and sometimes it's much narrower (especially when I take it my glasses to give my eyes a bit it rest).

To be honest, I don't see any reason to hard-wrap messages, when a terminal emulator can do automatic wrapping, optimally adjusted to the window.  

I was perfectly happy with the way it worked with sbotools 2.7.
