### ISSUE TITLE
"A fatal script error has occurred: Error when parsing file…"

### ISSUE THREAD

**Issue by Geremia** [pghvlaans/sbotools#18]
* Command entered: `sbocheck`

* Running version of `sbotools`: 3.2.1

* Output of `cat /etc/slackware-version`: Slackware 15.0+

* Output of `sboconfig --list`:

<details><summary>Details</summary>
<p>

```
sboconfig -b|--build-ignore:
    BUILD_IGNORE=FALSE
sboconfig -C|--classic:
    CLASSIC=FALSE
sboconfig -d|--distclean:
    DISTCLEAN=FALSE
sboconfig -B|--branch:
    GIT_BRANCH=FALSE
sboconfig -g|--gpg-verify:
    GPG_VERIFY=FALSE
sboconfig -j|--jobs:
    JOBS=FALSE
sboconfig -o|--local-overrides:
    LOCAL_OVERRIDES=FALSE
sboconfig -c|--noclean:
    NOCLEAN=FALSE
sboconfig -p|--pkg-dir:
    PKG_DIR=FALSE
sboconfig -r|--repo:
    REPO=rsync://slackbuilds.org/slackbuilds/15.0
sboconfig -R|--rsync:
    RSYNC_DEFAULT=FALSE
sboconfig -s|--sbo-home:
    SBO_HOME=/usr/sbo
sboconfig -V|--slackware-version:
    SLACKWARE_VERSION=FALSE
```

</p>
</details> 

* Description:

{I'm using the `sbopkg` `REPO` (cf. [this comment](https://github.com/pghvlaans/sbotools/issues/17#issuecomment-2564553504) to #17 ), but even when using `sbosnap fetch` to fetch a clean repo, I get the same issue.}

`sbocheck` returns:
```
# sbocheck 
Updating SlackBuilds tree...
      5,701,805   4%  518.64kB/s    0:00:10 (xfr#1, to-chk=0/76856)   

Checking for updated SlackBuilds...A fatal script error has occurred:
Error when parsing file python2-BeautifulSoup4.info.
Exiting.
```

Running `git fsck --full` on the repo returned that it was 100% 🆗.

`sbocheck -n` returns the same error.

**Comment by pghvlaans** [comment]
Thanks for the report!

It definitely has nothing to do with the location of your local repo. Several `info` files went in to the repo without a closing quotation mark for `EMAIL`, which is causing the crash. That should 100% be handled differently.

**Comment by pghvlaans** [comment]
This bug dates back to sbotools-2.x. If an info file is missing quotation marks, the program errors out ungracefully. Things should be working properly with commit [c03c9fe](https://github.com/pghvlaans/sbotools/commit/c03c9fe8f40c7d86aaaaf9eac3aed7db7c6553d6), which adds code to replace missing quotation marks and backslashes.

For anyone who runs into this issue, here are a few options for working around it:

1. Use your own fork of SBo if you have one.
2. Fix the files locally and refrain from running `sbocheck` without `-n` until the next public update.
3. Copy the affected directories into the local overrides directory (set with `sboconfig -o`) and fix them there; feel free to run `sbocheck` as usual.
4. Upgrade `sbotools` to commit c03c9fe. Download [the correct commit](https://github.com/pghvlaans/sbotools-git-slackbuild/commit/8a99a960966f0990dc641813237a5c87391bd234) from `sbotools-git-slackbuild` with [this link](https://github.com/pghvlaans/sbotools-git-slackbuild/archive/8a99a960966f0990dc641813237a5c87391bd234.zip). Unzip, download the source and run.

@Geremia, I'm going to leave this open until the fixed info files are in the public update.

**Comment by Geremia** [comment]
@pghvlaans What do you mean by "Fix the files locally"?

Also, I get the same issue with 937810b:
```
# sbocheck -n
Not updating the SlackBuilds tree...

Checking for updated SlackBuilds...A fatal script error has occurred:
Error when parsing file anki.info.
Exiting.
```

**Comment by pghvlaans** [comment]
Oh, just to add the missing quotation mark to the info files. There are ten of them.

Would you mind double-checking that 937801b is installed and not c03c9fe? Thanks.

**Comment by pghvlaans** [comment]
0f05b88 takes care of blank lines as well. I ran sbofind on every script in the 15.0 repository to verify that the error is avoided.

The sbotools-git-slackbuild commit is 7576f8e and the download link is [here](https://github.com/pghvlaans/sbotools-git-slackbuild/archive/7576f8e9bca981fcc1701a855e7c3f72cb40cc71.zip)

**Comment by Geremia** [comment]
@pghvlaans

> Would you mind double-checking that [937810b](https://github.com/pghvlaans/sbotools/commit/937810ba9c5f570f557067deb41942ca1dc267ba) is installed and not [c03c9fe](https://github.com/pghvlaans/sbotools/commit/c03c9fe8f40c7d86aaaaf9eac3aed7db7c6553d6)?

Woops I had c03c9fe, but it was tripping on a different info file than 3.2.1.

> The sbotools-git-slackbuild commit is 7576f8e and the download link is [here](https://github.com/pghvlaans/sbotools-git-slackbuild/archive/7576f8e9bca981fcc1701a855e7c3f72cb40cc71.zip)

That worked. Thanks.
