### ISSUE TITLE
Question: Has anyone been using `sboremove --nointeractive`?

### ISSUE THREAD

**Issue by pghvlaans** [pghvlaans/sbotools#2]
This is (well, was) an undocumented feature that allows `sboremove` to uninstall packages without prompting the user. It was removed in d4fd0c9.

My personal opinion is that it's dangerous and not particularly useful, but I'd be happy to put it back in if anyone needs it for scripting. Just let me know, and I'll take care of it.

**Comment by pghvlaans** [comment]
If `nointeractive` does get re-added, it will be documented this time.

**Comment by drgibbon** [comment]
Never used it myself, does seem potentially dangerous.
