### ISSUE TITLE
Feature Request: Rebuild all Packages option in sboinstall

### ISSUE THREAD

**Issue by Charadon** [pghvlaans/sbotools#4]
Sometimes when using -current, you just want to rebuild all packages. Currently the best way you can do this is to run a long shell command like this:

```bash
find /var/lib/pkgtools/packages -name "*SBo" | awk -F '-[0-9]' '{print $1}' | awk -F '/' '{print $6}' | tr '\n' ' ' | xargs -o -t sboinstall -r --reinstall
```

If it could be simplified to something like:

```bash
sboinstall --reinstall-all
```

I would be your bestest friend in the whole wide world 🥲

**Comment by pghvlaans** [comment]
I'll think of something a little more visually distinct for the flag name, but that's an interesting idea.

**Comment by pghvlaans** [comment]
`sboinstall --mass-rebuild` will generate build queues and rebuild/reinstall all _SBo SlackBuilds. It doesn't handle compat32 builds, so those will need to be dealt with separately. To skip the interactive prompts, use `sboinstall -r --mass-rebuild`; this has the added perk of automatically applying saved build options.

@Charadon, I'll leave the issue open for a few days in case you want to try it out and leave feedback (see [pghvlaans/sbotools-git-slackbuild](https://github.com/pghvlaans/sbotools-git-slackbuild/)). Thanks very much for the feature request!

**Comment by Charadon** [comment]
> Before releasing 3.1, I'll plan to add some kind of 'resume' functionality for non-interactive mass rebuilds in case of unexpected -current compatibility issues, bad downloads, etc.

I tried it out, I think there needs to be a blacklist feature before non-interactive will work. For example: If something depends on java, it'll try to grab the slackbuild where you compile java instead of the zulu one, which on my system will fail every single time.

**Comment by pghvlaans** [comment]
> I tried it out, I think there needs to be a blacklist feature before non-interactive will work.

I'd been thinking about adding a blacklist, actually. The main reason I haven't pulled the trigger is that I was concerned about broken builds, but a simple one that doesn't use regex and just prevents the members from being queued might do the trick.

Either way, back to the drawing board.

**Comment by Charadon** [comment]
> > I tried it out, I think there needs to be a blacklist feature before non-interactive will work.
> 
> I'd been thinking about adding a blacklist, actually. The main reason I haven't pulled the trigger is that I was concerned about broken builds, but a simple one that doesn't use regex and just prevents the members from being queued might do the trick.
> 
> Either way, back to the drawing board.

Yeah, a quick blacklist feature would probably be best for now. And probably easy to implement.

I would love to contribute as I am pretty knowledgeable in Perl, but I unfortunately don't know the codebase and don't have the time to study it on my own, especially with no dev documentation that I can see =(

**Comment by pghvlaans** [comment]
> Yeah, a quick blacklist feature would probably be best for now. And probably easy to implement.

Should be, especially if all it needs to do is keep single scripts from going into the queue or being removed (and deciding what to disable based on the blacklist was the only thing that gave me pause when I last looked at blacklist code).

Ideally, it should be possible for the user to ask for optional dependencies as well for e.g. `--mass-rebuild`, `sbofind -R` and `sboremove`. I'd like to do it in one file. Say someone wants `qemu` with a few optional dependencies and doesn't want `javacc` or `zulu-openjdk17`:

    !javacc
    !zulu-openjdk17
    libiscsi libnfs virtiofsd qemu

That's what I'm thinking at the moment, anyway.

> no dev documentation

This appears to have been generated and installed at one time, and the POD stuff is still there. If the state of the man pages as of 2.7 is anything to go by, though, some heavy editing would be needed. Definitely not for 3.1, but if it removes a barrier to contributing, putting that back in down the road would be worth it.

**Comment by pghvlaans** [comment]
With [9ebb828](https://github.com/pghvlaans/sbotools/commit/9ebb82870b4774ecdd98203bd6a9626fb5ed09a2), blacklisting and asking for optional dependencies should be ready to go. `/etc/sbotools/sbotools.hints` is the configuration file.

**Comment by pghvlaans** [comment]
And with that, `mass-rebuild` has resume capabilities. If the build is interrupted, a template file named `resume.temp` will be left in `SBO_HOME`; when `mass-rebuild` is used again, it will pick up from the script *after* the script that failed.
